[project]
name = "day14-quadrant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "groq>=1.7.0",
    "python-dotenv>=1.2.3",
    "qdrant-client>=1.19.0",
    "sentence-transformers>=6.0.0",
]

[tool.uv.workspace]
members = [
    "quadrant.py",
]
